import type { PresentationDeckConfig } from './types'

const baseDurationMs = 10_000
export const presentationDeckConfig: PresentationDeckConfig = {
  title: 'Лучшие практики',
  subtitle: 'Как мы строим аналитические панели для анализа, мониторинга и отчётности',
  leadCaption: 'на примере более 7 работающих систем',
  autoplay: true,
  transitionHoldMs: 280,
  sections: [
    {
      id: 'layout',
      title: 'Компоновка блоков и сетка',
      description: 'Показываем, как собираем плотные dashboard-композиции без потери читаемости.',
      startSlideId: 'layout-grid',
    },
    {
      id: 'widgets',
      title: 'Интерактивные виджеты',
      description: 'Переиспользуемые сценарии визуализации и управляемые под-слайды.',
      startSlideId: 'widget-types',
    },
    {
      id: 'filters',
      title: 'Гибкие фильтры и настройки',
      description: 'Фокус на сценариях отбора, состояниях форм и управлении представлением.',
      startSlideId: 'filters-basic',
    },
    {
      id: 'details',
      title: 'Детализация данных',
      description: 'Переход от summary к drill-down экранам и предметным карточкам.',
      startSlideId: 'details-cards',
    },
  ],
  slides: [
    {
      id: 'layout-grid',
      sectionId: 'layout',
      kind: 'sequence',
      title: 'Компоновка блоков и сетка',
      homeCard: {
        title: 'Компоновка<br />блоков и сетка',
        titleMaxWidth: '330px',
        imagePath: '/presentation/slides/componovka.webp',
        imageLayout: {
          variant: 'bottomLeft',
          scale: 1.2,
          offsetX: -200,
          offsetY: 140,
          rotateDeg: -5,
        },
        size: 'wide',
      },
      steps: [
        {
          id: 'layout-grid-step-1',
          projectTitle: 'Отчёт по реализации ЖУВ',
          projectUrl: 'https://kao-qas-bi01:8110/zhuvl/#/main',
          description: 'Система автоматизации сбора данных, анализа эффективности ЖУВ и прогнозирования цен на рынках',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/1-1.webp', objectFit: 'cover' },
        },
        {
          id: 'layout-grid-step-2',
          projectTitle: 'Реализация газа на внутреннем рынке',
          projectUrl: 'https://kao-prd-bal03/gasRealization/',
          description: 'Интерактивная страница сервисов Департамента 314',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/1-2.webp', objectFit: 'cover' },
        },
        {
          id: 'layout-grid-step-3',
          projectTitle: 'Мониторинг обеспеченности НП розничной сети ГНП Холдинг',
          projectUrl: 'https://kao-dev-bi01:8110/azs',
          description: 'Аналитический сервис по мониторингу АЗС ПАО "Газпром"',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/1-3.webp', objectFit: 'cover' },
        },
        {
          id: 'layout-grid-step-4',
          projectTitle: 'Контроль производственно-хозяйственной деятельности',
          projectUrl: 'https://kao-dev-bi01:8110/balance_monitoring_v2/',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/1-4.webp', objectFit: 'cover' },
        },
        {
          id: 'layout-grid-step-5',
          title: 'Сценарий 5',
          projectTitle: 'Учёт доходов и коммерческих расходов',
          projectUrl: 'https://kao-qas-bi01:8110/zhuvl816/#/analyze',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/1-5.webp', objectFit: 'cover' },
        },
      ],
      next: {
        kind: 'section',
        label: 'Следующий раздел',
        description: 'Интерактивные виджеты',
        targetSlideId: 'widget-types',
      },
    },
    {
      id: 'widget-types',
      sectionId: 'widgets',
      kind: 'selector',
      title: 'Интерактивные виджеты',
      stepButtonsTitle: 'Виды графиков',
      homeCard: {
        title: 'Интерактивные<br />виджеты',
        titleMaxWidth: '330px',
        imagePath: '/presentation/slides/iteract.webp',
        imageLayout: {
          variant: 'right',
          scale: 1.00,
          offsetX: 46,
          offsetY: 38,
        },
        size: 'wide',
      },
      steps: [
        {
          id: 'widget-area',
          title: 'Площадные',
          buttonLabel: 'Площадные',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/2-1.webp' },
          imageAlt: 'Площадные графики',
        },
        {
          id: 'widget-circle',
          title: 'Круговые',
          buttonLabel: 'Круговые',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/2-2.webp' },
          imageAlt: 'Круговые диаграммы',
        },
        {
          id: 'widget-line',
          title: 'Линейные',
          buttonLabel: 'Линейные',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/2-3.webp' },
          imageAlt: 'Линейные графики',
        },
        {
          id: 'widget-bar',
          title: 'Столбчатые',
          buttonLabel: 'Столбчатые',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/2-4.webp' },
          imageAlt: 'Столбчатые графики',
        },
        {
          id: 'widget-geo',
          title: 'Географические',
          buttonLabel: 'Географические',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/2-5.webp' },
          imageAlt: 'Географические визуализации',
        },
        {
          id: 'widget-sankey',
          title: 'Санкей',
          buttonLabel: 'Санкей',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/2-6.webp' },
          imageAlt: 'Диаграмма Санкей',
        },
      ],
      next: {
        kind: 'section',
        label: 'Следующий раздел',
        description: 'Гибкие фильтры и настройки',
        targetSlideId: 'filters-basic',
      },
    },
    {
      id: 'filters-basic',
      sectionId: 'filters',
      kind: 'sequence',
      title: 'Гибкие фильтры и настройки',
      homeCard: {
        title: 'Гибкие фильтры и настройки',
        titleMaxWidth: '860px',
        imagePath: '/presentation/slides/flexable.webp',
        imageLayout: {
          variant: 'bottomCenter',
          scale: 1,
          offsetX: 0,
          offsetY: 30,
        },
        size: 'wide',
      },
      steps: [
        {
          id: 'filters-basic-step',
          projectTitle: 'Настройки отображения отчётности',
          description: 'Проектируем гибкие и удобные фильтры, решающие задачи пользователей и повышающие эффективность работы с данными',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/3-1.webp' },
        },
        {
          id: 'filters-basic-step-2',
          projectTitle: 'Тёмная тема',
          description: 'Внедряем тёмную тему, для уменьшения утомления глаз при работе с большим количеством данных, улучшения фокуса на ключевых метриках, персонализации интерфейса',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/3-2.webp' },
        },
      ],
      next: {
        kind: 'section',
        label: 'Следующий раздел',
        description: 'Детализация данных',
        targetSlideId: 'details-cards',
      },
    },
    {
      id: 'details-cards',
      sectionId: 'details',
      kind: 'basic',
      title: 'Детализация данных',
      homeCard: {
        title: 'Детализация<br />данных',
        titleMaxWidth: '230px',
        imagePath: '/presentation/slides/detail.svg',
        imageLayout: {
          variant: 'bottomRight',
          scale: 1.12,
          offsetX: 30,
          offsetY: 0,
        },
        size: 'compact',
      },
      steps: [
        {
          id: 'details-overview',
          title: 'Карточка объекта',
          projectTitle: 'Доступность информации',
          description: 'Показываем дополнительные метрики, расширяющие контекст, изменения за период и источники данных с помощью привычных элементов интерфейса — тултипов и модальных окон.',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/4-1.webp' },
          imageAlt: 'Карточка объекта и блок детализации данных',
        },
      ],
    },
  ],
}
