import type { PresentationDeckConfig } from './types'

const baseDurationMs = 10_000
export const presentationDeckConfig: PresentationDeckConfig = {
  title: 'Лучшие практики',
  subtitle: 'Как мы строим аналитические панели для анализа, мониторинга и отчётности',
  leadCaption: 'на примере более 7 работающих систем',
  autoplay: true,
  transitionHoldMs: 280,
  sections: [
    {
      id: 'layout',
      title: 'Компоновка блоков и сетка',
      description: 'Показываем, как собираем плотные dashboard-композиции без потери читаемости.',
      startSlideId: 'layout-grid',
    },
    {
      id: 'widgets',
      title: 'Интерактивные виджеты',
      description: 'Переиспользуемые сценарии визуализации и управляемые под-слайды.',
      startSlideId: 'widget-types',
    },
    {
      id: 'filters',
      title: 'Гибкие фильтры и настройки',
      description: 'Фокус на сценариях отбора, состояниях форм и управлении представлением.',
      startSlideId: 'filters-basic',
    },
    {
      id: 'details',
      title: 'Детализация данных',
      description: 'Переход от summary к drill-down экранам и предметным карточкам.',
      startSlideId: 'details-cards',
    },
  ],
  slides: [
    {
      id: 'layout-grid',
      sectionId: 'layout',
      kind: 'sequence',
      title: 'Компоновка блоков и сетка',
      homeCard: {
        title: 'Компоновка блоков и сетка',
        description: 'Плотные рабочие экраны с понятной иерархией',
        imagePath: '/presentation/slides/componovka.png',
        imageLayout: {
          variant: 'bottomLeft',
          scale: 1.2,
          offsetX: -200,
          offsetY: 140,
          rotateDeg: -5,
        },
        size: 'wide',
      },
      steps: [
        {
          id: 'layout-grid-step-1',
          title: 'Сценарий 1',
          projectTitle: 'Отчёт по реализации ЖУВ',
          projectUrl: '#/slides/layout-grid',
          description: 'Система автоматизации сбора данных, анализа эффективности ЖУВ и прогнозирования цен на рынках',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/1-1.jpg', objectFit: 'cover' },
        },
        {
          id: 'layout-grid-step-2',
          title: 'Сценарий 2',
          projectTitle: 'Реализация газа на внутреннем рынке',
          projectUrl: '#/slides/layout-grid',
          description: 'Сбор и визуализация данных о поставке газа РФ, анализа задолженности, прогноз спроса на газ в РФ на 10 лет, отчёт о реализации газа',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/1-2.jpg', objectFit: 'cover' },
        },
        {
          id: 'layout-grid-step-3',
          title: 'Сценарий 3',
          projectTitle: 'Мониторинг обеспеченности НП розничной сети ГНП Холдинг',
          projectUrl: '#/slides/layout-grid',
          description: 'Сбор и визуализация данных о поставке газа РФ, анализа задолженности, прогноз спроса на газ в РФ на 10 лет, отчёт о реализации газа',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/1-3.jpg', objectFit: 'cover' },
        },
        {
          id: 'layout-grid-step-4',
          title: 'Сценарий 4',
          projectTitle: 'Контроль производственно-хозяйственной деятельности',
          projectUrl: '#/slides/layout-grid',
          description: 'Описание',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/1-4.jpg', objectFit: 'cover' },
        },
        {
          id: 'layout-grid-step-5',
          title: 'Сценарий 5',
          projectTitle: 'Учёт доходов и коммерческих расходов',
          projectUrl: '#/slides/layout-grid',
          description: 'Описание',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/1-5.jpg', objectFit: 'cover' },
        },
      ],
      next: {
        kind: 'section',
        label: 'Следующий раздел',
        description: 'Интерактивные виджеты',
        targetSlideId: 'widget-types',
      },
    },
    {
      id: 'widget-types',
      sectionId: 'widgets',
      kind: 'selector',
      title: 'Интерактивные виджеты',
      infoLabel: 'Тип визуализации',
      stepButtonsTitle: 'Виды графиков',
      showInfoCard: false,
      homeCard: {
        title: 'Интерактивные виджеты',
        description: 'Компоненты и паттерны, переключаемые по сценарию пользователя',
        imagePath: '/presentation/slides/iteract.png',
        imageLayout: {
          variant: 'right',
          scale: 1.00,
          offsetX: 46,
          offsetY: 38,
        },
        size: 'wide',
      },
      steps: [
        {
          id: 'widget-area',
          title: 'Площадные',
          buttonLabel: 'Площадные',
          projectTitle: 'Площадные графики',
          projectUrl: '#/slides/widget-types',
          description: 'Площадные графики помогают быстро показать диапазон и тренд в многосерийной аналитике, не перегружая экран деталями.',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/iteract.png' },
          imageAlt: 'Площадной график и интерактивный виджет',
        },
        {
          id: 'widget-circle',
          title: 'Круговые',
          buttonLabel: 'Круговые',
          projectTitle: 'Круговые диаграммы',
          projectUrl: '#/slides/widget-types',
          description: 'Круговые диаграммы используются там, где важно быстро считать долю и распределение структуры без лишней легенды.',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/images/lahta.svg' },
          imageAlt: 'Круговая диаграмма в аналитическом интерфейсе',
        },
        {
          id: 'widget-line',
          title: 'Линейные',
          buttonLabel: 'Линейные',
          projectTitle: 'Линейные графики',
          projectUrl: '#/slides/widget-types',
          description: 'Линейные графики поддерживают быстрый анализ тренда, анимацию обновлений и точечные hover-сценарии для динамических данных.',
          durationMs: baseDurationMs,
          media: { kind: 'widget', widgetKey: 'analyticsDashboard' },
          imageAlt: 'Интерактивный линейный React-виджет',
        },
        {
          id: 'widget-bar',
          title: 'Столбчатые',
          buttonLabel: 'Столбчатые',
          projectTitle: 'Столбчатые панели',
          projectUrl: '#/slides/widget-types',
          description: 'Столбчатая визуализация особенно полезна для сравнения сценариев, план-факта и рейтингов внутри одного экрана.',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/slides/flexable.png' },
          imageAlt: 'Столбчатые визуализации и панель сравнения',
        },
        {
          id: 'widget-sankey',
          title: 'Санкей',
          buttonLabel: 'Санкей',
          projectTitle: 'Диаграммы потоков',
          projectUrl: '#/slides/widget-types',
          description: 'Санкей и картографические паттерны подключаются тем же registry-механизмом, что и остальные шаги, без переписывания shell-логики.',
          durationMs: baseDurationMs,
          media: { kind: 'image', imagePath: '/presentation/images/hierarhical.svg' },
          imageAlt: 'Диаграмма потоков и схема маршрутов',
        },
      ],
      // next: {
      //   kind: 'section',
      //   label: 'Следующий раздел',
      //   description: 'Гибкие фильтры и настройки',
      //   targetSlideId: 'filters-basic',
      // },
    },
    // {
    //   id: 'filters-basic',
    //   sectionId: 'filters',
    //   kind: 'basic',
    //   title: 'Гибкие фильтры и настройки',
    //   homeCard: {
    //     title: 'Гибкие фильтры и настройки',
    //     description: 'Настройка срезов, сценариев и представления без перегрузки формы',
    //     imagePath: '/presentation/slides/flexable.png',
    //     imageLayout: {
    //       variant: 'bottomCenter',
    //       scale: 1,
    //       offsetX: 0,
    //       offsetY: 30,
    //     },
    //     size: 'wide',
    //   },
    //   steps: [
    //     {
    //       id: 'filters-basic-step',
    //       title: 'Фильтры',
    //       projectTitle: 'Конфигурируемые формы отбора',
    //       projectUrl: '#/slides/filters-basic',
    //       description: 'Базовый слайд показывает, как большие фильтровые формы собираются из типовых блоков и не теряют читаемость даже при высокой плотности параметров.',
    //       durationMs: baseDurationMs,
    //       media: { kind: 'image', imagePath: '/presentation/slides/flexable.png' },
    //       imageAlt: 'Экран с фильтрами, настройками и панелями выбора',
    //     },
    //   ],
    //   next: {
    //     kind: 'section',
    //     label: 'Следующий раздел',
    //     description: 'Детализация данных',
    //     targetSlideId: 'details-cards',
    //   },
    // },
    // {
    //   id: 'details-cards',
    //   sectionId: 'details',
    //   kind: 'hybrid',
    //   title: 'Детализация данных',
    //   infoLabel: 'О проекте',
    //   stepButtonsTitle: 'Этапы детализации',
    //   homeCard: {
    //     title: 'Детализация данных',
    //     description: 'Переход от summary к карточкам и оперативному drill-down',
    //     imagePath: '/presentation/slides/detail.svg',
    //     imageLayout: {
    //       variant: 'bottomRight',
    //       scale: 1.12,
    //       offsetX: 30,
    //       offsetY: 0,
    //     },
    //     size: 'compact',
    //   },
    //   steps: [
    //     {
    //       id: 'details-overview',
    //       title: 'Карточка объекта',
    //       buttonLabel: 'Карточка объекта',
    //       projectTitle: 'Карточки наблюдения',
    //       projectUrl: '#/slides/details-cards',
    //       description: 'Показываем компактную карточку объекта, чтобы пользователь быстро считал ключевые поля и не выпадал из сценария презентации.',
    //       durationMs: baseDurationMs,
    //       media: { kind: 'image', imagePath: '/presentation/slides/detail.svg' },
    //       imageAlt: 'Карточка объекта и блок детализации данных',
    //     },
    //     {
    //       id: 'details-summary',
    //       title: 'Контекст рядом',
    //       buttonLabel: 'Контекст рядом',
    //       projectTitle: 'Соседний контекст',
    //       projectUrl: '#/slides/details-cards',
    //       description: 'Гибридный режим даёт и счётчик прогресса, и быстрый доступ к шагам справа, чтобы не терять управляемость на длинных историях показа.',
    //       durationMs: baseDurationMs,
    //       media: { kind: 'image', imagePath: '/presentation/images/lahta.svg' },
    //       imageAlt: 'Контекстные карточки рядом с крупным рабочим полотном',
    //     },
    //     {
    //       id: 'details-widget',
    //       title: 'Интерактивный разбор',
    //       buttonLabel: 'Интерактивный разбор',
    //       projectTitle: 'Виджет drill-down',
    //       projectUrl: '#/slides/details-cards',
    //       description: 'На этом шаге вместо статического изображения можно показать React-компонент и продемонстрировать интерактивный drill-down прямо в презентации.',
    //       durationMs: baseDurationMs,
    //       media: { kind: 'widget', widgetKey: 'analyticsDashboard' },
    //       imageAlt: 'Интерактивный виджет drill-down',
    //     },
    //   ],
    // },
  ],
}
